name: Build plugin
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -q CursedValleyCore.zip -d unzipped
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: temurin
      - run: mvn -B clean package
        working-directory: unzipped/CursedValleyCore
      - uses: actions/upload-artifact@v4
        with:
          name: CursedValleyCore
          path: unzipped/CursedValleyCore/target/*.jar
